import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { useEffect } from "react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Create T3 App</h1>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  const createMailer = api.mailer.create.useMutation();
  const mailers = api.mailer.getAll.useQuery();

  useEffect(() => {
    if (sessionData?.user) {
      const result = createMailer.mutate({
        name: "GAAA",
        activate: true,
        smtpHost: "gmail.smtp.com",
        smtpUser: "darwin97.va@gmail.com",
        smtpPass: "aeaMano",
        smtpName: "cherok",
      });

      console.log(result, "result");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionData?.user]);

  console.log(mailers);

  return (
    <div>
      <p>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
